In [8]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("Dados originais_artigo Priscila .xlsx")

In [3]:
df.head()

,Espécie - Abelha,Freq. 1 (Hz),Freq. 2 (Hz),Freq. 3 (Hz),Média Freq.,Peso abelha (g),Tamanho tórax,Duração (s),Média Freq..1,Peso abelha (g).1,Tamanho tórax.1,Duração (s).1
0,Augochloropsis_sp1,219.4,197.3,203.7,206.800000,0.0608,2.1,4.1780,15.62052,0.007294,0.122474,1.570395
1,Augochloropsis_sp1,206.4,205.1,216.0,209.166667,0.0608,2.1,1.6670,NaN,NaN,NaN,NaN
2,Augochloropsis_sp1,187.3,186.6,204.0,192.633333,0.0448,1.9,0.5803,NaN,NaN,NaN,NaN
3,Augochloropsis_sp1,234.7,229.3,214.8,226.266667,0.0534,1.9,0.7520,NaN,NaN,NaN,NaN
4,Augochloropsis_sp1,214.6,194.8,205.8,205.066667,0.0448,1.9,NaN,NaN,NaN,NaN,NaN

In [4]:
dados = df.drop(["Peso abelha (g)", "Tamanho tórax", "Duração (s)", "Média Freq..1",\
                            "Peso abelha (g).1", "Tamanho tórax.1", "Duração (s).1"], axis=1)

In [5]:
dados.head()

     Espécie - Abelha   Freq. 1 (Hz)   Freq. 2 (Hz)  Freq. 3 (Hz)  Média Freq.
0  Augochloropsis_sp1          219.4          197.3         203.7   206.800000
1  Augochloropsis_sp1          206.4          205.1         216.0   209.166667
2  Augochloropsis_sp1          187.3          186.6         204.0   192.633333
3  Augochloropsis_sp1          234.7          229.3         214.8   226.266667
4  Augochloropsis_sp1          214.6          194.8         205.8   205.066667

In [6]:
target_names = dados["Espécie - Abelha"].unique()
target_names

array(['Augochloropsis_sp1', 'Augochloropsis_sp2',
       'Augochloropsis_brachycephala', 'Bombus_pauloensis',
       'Bombus_morio', 'Centris_tarsata', 'Centris_trigonoides',
       'Eulaema_nigrita', 'Exomalopsis_analis', 'Exomalopsis_minor',
       'Melipona_bicolor', 'Melipona_quadrifasciata',
       'Xylocopa_nigrocincta', 'Xylocopa_suspecta',
       'Pseudoalglochloropsis_graminea'], dtype=object)

In [9]:
lista_especies = []

for especie in target_names:
    #Filtra o DataFrame por espécie
    d = dados[dados["Espécie - Abelha"] == especie]
    
    #Junta todas as frequências por espécie
    #lista_freq = list(d[' Freq. 1 (Hz)']) + list(d[' Freq. 2 (Hz)']) + list(d['Freq. 3 (Hz)'])
       
    #Calcula o desvio padrão
    #dvp = np.std(lista_freq)
    dvp = np.std(d['Média Freq.'])
    
    #Calcula a média das médias
    media = d['Média Freq.'].mean()

    #Cria um dicionário com o desvio padrão e a média
    lista_especies.append([especie, media, dvp])

In [10]:
media_desvio_padrao = pd.DataFrame(lista_especies, columns=['Espécies', 'Média', 'Desvio Padrão'])

In [11]:
media_desvio_padrao

                          Espécies       Média  Desvio Padrão
0               Augochloropsis_sp1  203.372222      14.259518
1               Augochloropsis_sp2  190.100000       0.000000
2     Augochloropsis_brachycephala  252.183333      44.283333
3                Bombus_pauloensis  233.977778      20.526520
4                     Bombus_morio  218.395833      17.522148
5                  Centris_tarsata  330.808081       0.000000
6              Centris_trigonoides  319.983333       7.950000
7                  Eulaema_nigrita  196.733333       0.000000
8               Exomalopsis_analis  167.620000      20.926730
9                Exomalopsis_minor  151.993333      11.326104
10                Melipona_bicolor  337.195833      25.768006
11         Melipona_quadrifasciata  323.075000       5.646453
12            Xylocopa_nigrocincta  247.250000       3.416667
13               Xylocopa_suspecta  250.166667      29.133333
14  Pseudoalglochloropsis_graminea  210.500000       6.846627